### ISSUE TITLE
German translation contains English words

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-i18n#100]
https://github.com/Rise-Vision/common-i18n/blob/master/dist/locales/translation_de.json

**Comment by ByronDarlison** [comment]
@alex-deaconu can you confirm if this defect is still open and if it is exactly what needs to be done to fix this?

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QdJYk0XO&#x2F;1105-issues-common-i18n-5-open"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issues: common-i18n {5 open}</a>

**Comment by alex-deaconu** [comment]
@ByronDarlison yes it is still open. The only file that actually has German translations is https://github.com/Rise-Vision/common-i18n/blob/master/src/locales_json/de/common.json. The others are English. We can just remove those files (with English translations) to fix this issue.

Thanks.

**Comment by ByronDarlison** [comment]
Alex, don't worry about this one. I'd like to tackle international markets
later. Thanks!
