### ISSUE TITLE
LOCALES_SUFIX variable is misspelled

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/common-i18n#21]
The LOCALES_SUFIX variable should be LOCALES_SUFFIX. Although this isn't a huge deal, it is incorrect. I think that it would be best if this were fixed and a new version tagged to prevent breaking other projects that use this repo.

**Comment by ByronDarlison** [comment]
@donnapep is this still open? And if it is, @alex-deaconu @ezequielc do you concur with the suggested fix? Thanks!

**Comment by donnapep** [comment]
@ByronDarlison Yes, it's still open, but probably not high on the priority list.

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QdJYk0XO&#x2F;1105-issues-common-i18n-5-open"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issues: common-i18n {5 open}</a>

**Comment by ByronDarlison** [comment]
@donnapep okay. I would like to tackle this as part of an internationalization epic that we will be taking on later. Thanks
