### ISSUE TITLE
.po file should be created in addition to .json files

### ISSUE THREAD

**Issue by donnapep** [Rise-Vision/common-i18n#24]
A .po file should be generated so that anyone wanting to translate our apps and Widgets into other languages can do so.

**Comment by ByronDarlison** [comment]
@donnapep @fjvallarino can you clarify what area this applies to? Where does this problem exist? Thanks

**Comment by donnapep** [comment]
@ByronDarlison This has already been implemented. Thx.

**Comment by ByronDarlison** [comment]
@donnapep thanks
