### ISSUE TITLE
Also update locales_json on build

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/common-i18n#48]
Currently, `gulp build` only updates /dist/. If a developer changes .po files, the locales_json files are not updated.

This means that `gulp json-to-po` will undo any .po changes previously made that weren't matched in the .json files.

**Comment by ByronDarlison** [comment]
@alex-deaconu is this still open? Thanks

**Comment by ByronDarlison** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;QdJYk0XO&#x2F;1105-issues-common-i18n-5-open"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Issues: common-i18n {5 open}</a>

**Comment by alex-deaconu** [comment]
@ByronDarlison double checked, this was fixed. Closing. Thanks.

**Comment by ByronDarlison** [comment]
Thanks!
